"""API request/response schemas."""

from .admin import (
    AdminActivityLogListResponse,
    AdminActivityLogRequest,
    AdminActivityLogResponse,
    AdminDashboardCreateRequest,
    AdminDashboardResponse,
    AdminDashboardUpdateRequest,
    AdminLoginRequest,
    AdminLoginResponse,
    AdminPasswordChangeRequest,
    AdminPasswordResetRequest,
    AdminRoleCreateRequest,
    AdminRoleResponse,
    AdminRoleUpdateRequest,
    AdminSessionResponse,
    AdminStatsResponse,
    AdminUserCreateRequest,
    AdminUserListResponse,
    AdminUserResponse,
    AdminUserUpdateRequest,
    SystemSettingCreateRequest,
    SystemSettingResponse,
    SystemSettingUpdateRequest,
)
from .health_details import (
    CPUHealthDetails,
    DatabaseHealthDetails,
    HealthDetails,
    MemoryHealthDetails,
    RedisHealthDetails,
)
from .quote import (
    QuoteBulkActionRequest,
    QuoteBulkActionResponse,
    QuoteCalculateRequest,
    QuoteCalculateResponse,
    QuoteCompareRequest,
    QuoteCompareResponse,
    QuoteConvertRequest,
    QuoteConvertResponse,
    QuoteCreateRequest,
    QuoteListResponse,
    QuoteResponse,
    QuoteSearchRequest,
    QuoteUpdateRequest,
)

__all__ = [
    # Health schemas
    "DatabaseHealthDetails",
    "RedisHealthDetails",
    "MemoryHealthDetails",
    "CPUHealthDetails",
    "HealthDetails",
    # Quote schemas
    "QuoteCreateRequest",
    "QuoteUpdateRequest",
    "QuoteResponse",
    "QuoteListResponse",
    "QuoteCalculateRequest",
    "QuoteCalculateResponse",
    "QuoteCompareRequest",
    "QuoteCompareResponse",
    "QuoteConvertRequest",
    "QuoteConvertResponse",
    "QuoteSearchRequest",
    "QuoteBulkActionRequest",
    "QuoteBulkActionResponse",
    # Admin schemas
    "AdminRoleCreateRequest",
    "AdminRoleUpdateRequest",
    "AdminRoleResponse",
    "AdminUserCreateRequest",
    "AdminUserUpdateRequest",
    "AdminUserResponse",
    "AdminUserListResponse",
    "AdminPasswordChangeRequest",
    "AdminPasswordResetRequest",
    "SystemSettingCreateRequest",
    "SystemSettingUpdateRequest",
    "SystemSettingResponse",
    "AdminActivityLogRequest",
    "AdminActivityLogResponse",
    "AdminActivityLogListResponse",
    "AdminDashboardCreateRequest",
    "AdminDashboardUpdateRequest",
    "AdminDashboardResponse",
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminSessionResponse",
    "AdminStatsResponse",
]
