# PolicyCore - Policy Decision Management System
# Copyright (C) 2025 Luiz Frias <luizf35@gmail.com>
# Form F[x] Labs
#
# This software is dual-licensed under AGPL-3.0 and Commercial License.
# For commercial licensing, contact: luizf35@gmail.com
# See LICENSE file for full terms.

"""API request/response schemas."""

from .admin import (
    AdminActivityLogListResponse,
    AdminActivityLogRequest,
    AdminActivityLogResponse,
    AdminDashboardCreateRequest,
    AdminDashboardResponse,
    AdminDashboardUpdateRequest,
    AdminLoginRequest,
    AdminLoginResponse,
    AdminPasswordChangeRequest,
    AdminPasswordResetRequest,
    AdminRoleCreateRequest,
    AdminRoleResponse,
    AdminRoleUpdateRequest,
    AdminSessionResponse,
    AdminStatsResponse,
    AdminUserCreateRequest,
    AdminUserListResponse,
    AdminUserResponse,
    AdminUserUpdateRequest,
    SystemSettingCreateRequest,
    SystemSettingResponse,
    SystemSettingUpdateRequest,
)
from .compliance import (
    AccessControlMatrixResult,
    AuditLogEntry,
    AuditTrailSummary,
    AvailabilityMetrics,
    BackupValidation,
    ComplianceReport,
    ComplianceStatus,
    ConfidentialitySettings,
    ConsentManagementRecord,
    ControlTestFinding,
    ControlTestingDashboard,
    ControlTestResult,
    DataClassificationResult,
    DataSubjectRightsRequest,
    EvidenceCollection,
    EvidenceItem,
    PerformanceBaseline,
    PrivacyControlSettings,
    RiskLevel,
    SecurityAssessment,
    SecurityControlConfig,
    TrustServiceCriterion,
    VulnerabilityFinding,
    create_audit_log_entry,
    create_control_test_result,
    create_evidence_item,
)
from .health_details import (
    CPUHealthDetails,
    DatabaseHealthDetails,
    HealthDetails,
    MemoryHealthDetails,
    RedisHealthDetails,
)
from .quote import (
    QuoteBulkActionRequest,
    QuoteBulkActionResponse,
    QuoteCalculateRequest,
    QuoteCalculateResponse,
    QuoteCompareRequest,
    QuoteCompareResponse,
    QuoteConvertRequest,
    QuoteConvertResponse,
    QuoteCreateRequest,
    QuoteListResponse,
    QuoteResponse,
    QuoteSearchRequest,
    QuoteUpdateRequest,
)

__all__ = [
    # Health schemas
    "DatabaseHealthDetails",
    "RedisHealthDetails",
    "MemoryHealthDetails",
    "CPUHealthDetails",
    "HealthDetails",
    # Quote schemas
    "QuoteCreateRequest",
    "QuoteUpdateRequest",
    "QuoteResponse",
    "QuoteListResponse",
    "QuoteCalculateRequest",
    "QuoteCalculateResponse",
    "QuoteCompareRequest",
    "QuoteCompareResponse",
    "QuoteConvertRequest",
    "QuoteConvertResponse",
    "QuoteSearchRequest",
    "QuoteBulkActionRequest",
    "QuoteBulkActionResponse",
    # Admin schemas
    "AdminRoleCreateRequest",
    "AdminRoleUpdateRequest",
    "AdminRoleResponse",
    "AdminUserCreateRequest",
    "AdminUserUpdateRequest",
    "AdminUserResponse",
    "AdminUserListResponse",
    "AdminPasswordChangeRequest",
    "AdminPasswordResetRequest",
    "SystemSettingCreateRequest",
    "SystemSettingUpdateRequest",
    "SystemSettingResponse",
    "AdminActivityLogRequest",
    "AdminActivityLogResponse",
    "AdminActivityLogListResponse",
    "AdminDashboardCreateRequest",
    "AdminDashboardUpdateRequest",
    "AdminDashboardResponse",
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminSessionResponse",
    "AdminStatsResponse",
    # Compliance schemas
    "AccessControlMatrixResult",
    "AuditLogEntry",
    "AuditTrailSummary",
    "AvailabilityMetrics",
    "BackupValidation",
    "ComplianceReport",
    "ComplianceStatus",
    "ConfidentialitySettings",
    "ConsentManagementRecord",
    "ControlTestFinding",
    "ControlTestResult",
    "ControlTestingDashboard",
    "DataClassificationResult",
    "DataSubjectRightsRequest",
    "EvidenceCollection",
    "EvidenceItem",
    "PerformanceBaseline",
    "PrivacyControlSettings",
    "RiskLevel",
    "SecurityAssessment",
    "SecurityControlConfig",
    "TrustServiceCriterion",
    "VulnerabilityFinding",
    "create_audit_log_entry",
    "create_control_test_result",
    "create_evidence_item",
]
