"""Domain models package for MVP Policy Decision Backend.

This package exports all Pydantic domain models with strict validation
and immutability for enterprise-grade insurance operations.
"""

from .base import BaseModelConfig, IdentifiableModel, TimestampedModel
from .claim import (
    Claim,
    ClaimBase,
    ClaimCreate,
    ClaimPriority,
    ClaimStatus,
    ClaimStatusUpdate,
    ClaimType,
    ClaimUpdate,
)
from .customer import (
    Customer,
    CustomerBase,
    CustomerCreate,
    CustomerStatus,
    CustomerType,
    CustomerUpdate,
)
from .policy import (
    Policy,
    PolicyBase,
    PolicyCreate,
    PolicyStatus,
    PolicyType,
    PolicyUpdate,
)
from .quote import (
    Quote,
    QuoteBase,
    QuoteCreate,
    QuoteUpdate,
    QuoteComparison,
    QuoteStatus,
    CoverageType,
    DiscountType,
    VehicleType,
    DriverRelationship,
    ContactMethod,
    ProductType,
    VehicleInfo,
    DriverInfo,
    CoverageSelection,
    Discount,
)
from .admin import (
    AdminUser,
    AdminUserBase,
    AdminUserCreate,
    AdminUserUpdate,
    AdminRole,
    AdminRoleModel,
    Permission,
    SystemSetting,
    SystemSettingCategory,
    AdminActivityLog,
    ActivityAction,
    AdminDashboard,
    AdminDashboardWidget,
    DashboardWidget,
)
from .user import (
    User,
    UserBase,
    UserCreate,
    UserUpdate,
    UserPasswordUpdate,
    UserLogin,
    UserLoginResponse,
    UserRefreshRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    EmailVerificationRequest,
    UserRole,
    UserStatus,
)

__all__ = [
    # Base models
    "BaseModelConfig",
    "TimestampedModel",
    "IdentifiableModel",
    # Policy models
    "PolicyBase",
    "Policy",
    "PolicyCreate",
    "PolicyUpdate",
    "PolicyType",
    "PolicyStatus",
    # Customer models
    "CustomerBase",
    "Customer",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerType",
    "CustomerStatus",
    # Claim models
    "ClaimBase",
    "Claim",
    "ClaimCreate",
    "ClaimUpdate",
    "ClaimStatusUpdate",
    "ClaimType",
    "ClaimStatus",
    "ClaimPriority",
    # Quote models
    "QuoteBase",
    "Quote",
    "QuoteCreate",
    "QuoteUpdate",
    "QuoteComparison",
    "QuoteStatus",
    "CoverageType",
    "DiscountType",
    "VehicleType",
    "DriverRelationship",
    "ContactMethod",
    "ProductType",
    "VehicleInfo",
    "DriverInfo",
    "CoverageSelection",
    "Discount",
    # Admin models
    "AdminUser",
    "AdminUserBase",
    "AdminUserCreate",
    "AdminUserUpdate",
    "AdminRole",
    "AdminRoleModel",
    "Permission",
    "SystemSetting",
    "SystemSettingCategory",
    "AdminActivityLog",
    "ActivityAction",
    "AdminDashboard",
    "AdminDashboardWidget",
    "DashboardWidget",
    # User models
    "User",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserLogin",
    "UserLoginResponse",
    "UserRefreshRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "EmailVerificationRequest",
    "UserRole",
    "UserStatus",
]
